### ISSUE TITLE
[bug] TiktokLiveRec stops recording and starts again.

### ISSUE THREAD

**Issue by babealiene5** [emako/TiktokLiveRec#13]
the live stops recording and then starts again on tiktok that is one recording stops in 10 minutes and start again in other file.

![image](https://github.com/user-attachments/assets/39d10c9c-3cf4-4ab7-b522-cadf3a60cd84)

**Comment by emako** [comment]
It is indeed designed that way, you need to manually disable it.

![image](https://github.com/user-attachments/assets/416a7111-5749-4058-a74b-975e6d94f014)

**Comment by emako** [comment]
https://github.com/emako/TiktokLiveRec/releases/tag/1.6.4
